Fix preexec check in lnet init script
The lnet init script was missing the "start" argument to the run_prexec_check
function which resulted in a syntax error.  This commit also adds the
run_postexec_check function and calls it after lnet services are started.  The
stop) case in the init script is now wrapped with calls to
run_[pre|post]exe_check "stop".

To improve flexibility, /etc/init.d/lnet will now source /etc/sysconfig/lnet
for configuration settings.  Previously, lustre and lnet shared a common
configuration file.  This change gives administrators the flexibility to
independently define pre and post exec actions for lnet and lustre.

Also, fix a few typos in comments in the lustre.in init script.

diff --git a/lustre/scripts/lnet b/lustre/scripts/lnet
--- a/lustre/scripts/lnet
+++ b/lustre/scripts/lnet
@@ -16,7 +16,7 @@
 [ "${NETWORKING}" = "no" ] && exit 0
 
 # Check for and source configuration file otherwise set defaults
-[ -f /etc/sysconfig/lustre ] && . /etc/sysconfig/lustre
+[ -f /etc/sysconfig/lnet ] && . /etc/sysconfig/lnet
 
 declare -r TOP_MODULES=(	\
 	obdecho			\
@@ -64,6 +64,20 @@ run_preexec_check ()
 	fi
 }
 
+# Usage: run_postexec_check [ start | restart | condrestart ]
+# The single parameter will be passed to the POSTEXEC_SCRIPT
+run_postexec_check ()
+{
+	if [ -n "$POSTEXEC_CHECK" ] && ! $POSTEXEC_CHECK ; then
+		echo "Post-exec check \"$POSTEXEC_CHECK\" failed.  Aborting."
+		exit 1
+	fi
+
+	if [ -n "$POSTEXEC_SCRIPT" ] && ! "$POSTEXEC_SCRIPT" "$1" ; then
+		echo "Post-exec script \"$POSTEXEC_SCRIPT\" failed.  Aborting."
+		exit 1
+	fi
+}
 
 remove_modules ()
 {
@@ -157,16 +171,19 @@ status ()
 # See how we were called.
 case "$1" in
   start)
-	run_preexec_check
+	run_preexec_check "start"
 	touch /var/lock/subsys/lnet
 	modprobe lnet || exit 1
 	lctl network up || exit 1
+	run_postexec_check "start"
 	;;
   stop)
+	run_preexec_check "stop"
 	remove_modules ${TOP_MODULES[*]} || exit 1
 	stop_lnet || exit 1
 	remove_modules ${BOTTOM_MODULES[*]} || exit 1
 	rm -f /var/lock/subsys/lnet
+	run_postexec_check "stop"
 	;;
   status)
 	status
